# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/discopipe',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/discopipe',
                'lib_path': 'discopipe'},
  'syms': { 'discopipe.bot': { 'discopipe.bot.Discopipe': ('bot.html#discopipe', 'discopipe/bot.py'),
                               'discopipe.bot.Discopipe.__init__': ('bot.html#discopipe.__init__', 'discopipe/bot.py'),
                               'discopipe.bot.Discopipe.on_message': ('bot.html#discopipe.on_message', 'discopipe/bot.py'),
                               'discopipe.bot.Discopipe.on_ready': ('bot.html#discopipe.on_ready', 'discopipe/bot.py'),
                               'discopipe.bot.compose': ('bot.html#compose', 'discopipe/bot.py'),
                               'discopipe.bot.load_config': ('bot.html#load_config', 'discopipe/bot.py'),
                               'discopipe.bot.main': ('bot.html#main', 'discopipe/bot.py'),
                               'discopipe.bot.reply_text': ('bot.html#reply_text', 'discopipe/bot.py'),
                               'discopipe.bot.run_agent': ('bot.html#run_agent', 'discopipe/bot.py')}}}
