# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/discopipe',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/discopipe',
                'lib_path': 'discopipe'},
  'syms': {'discopipe.bot': {'discopipe.bot.run_agent': ('bot.html#run_agent', 'discopipe/bot.py')}}}
