"""Discord passthrough to a headless coding agent CLI: subprocess runner,
reply shaping, env config, and the thin discord.py glue.

Docs: https://doyu.github.io/discopipebot.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_bot.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/00_bot.ipynb #46e89a50
pass  # Bot implementation starts here
