"""Discord passthrough to a headless coding agent CLI: subprocess runner,
reply shaping, env config, and the thin discord.py glue.

Docs: https://doyu.github.io/discopipebot.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_bot.ipynb.

# %% auto #0
__all__ = ['run_agent', 'compose', 'reply_text']

# %% ../nbs/00_bot.ipynb #22571ecb
import asyncio, os, signal

async def run_agent(text:str,            # message for the agent, fed to stdin
                    cmd:list,            # agent command line, already shlex-split
                    cwd:str,             # working directory for the agent
                    timeout:float=600.0, # wall-clock seconds before SIGKILL
                    )->tuple:            # (stdout, stderr, returncode)
    "Run one agent turn; never raises on nonzero exit or timeout."
    proc = await asyncio.create_subprocess_exec(
        *cmd, cwd=cwd, start_new_session=True,
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
    comm = asyncio.ensure_future(proc.communicate(text.encode()))
    try:
        out, err = await asyncio.wait_for(asyncio.shield(comm), timeout)
    except asyncio.TimeoutError:
        try: os.killpg(proc.pid, signal.SIGKILL)   # whole session: agent + children
        except ProcessLookupError: pass
        try:
            out, err = await asyncio.wait_for(asyncio.shield(comm), 1)
        except asyncio.TimeoutError:
            comm.cancel()
            return "… timed out (output withheld by a background child)\n", "", -9   # -9: killed by SIGKILL
        rc = proc.returncode if proc.returncode is not None else -9
        return out.decode(errors="replace") + "\n… timed out\n", err.decode(errors="replace"), rc
    return out.decode(errors="replace"), err.decode(errors="replace"), proc.returncode

# %% ../nbs/00_bot.ipynb #cell-task3-impl
_ZWSP = "​"   # breaks a literal ``` so stderr can't close the fence

def compose(out:str,    # agent stdout (markdown)
            err:str,    # agent stderr, captured separately
            rc:int,     # agent exit code
            )->str:     # reply body for Discord
    "stdout alone on success; append `(exit N)` + fenced stderr on failure."
    if not rc: return out
    body = err.strip().replace("```", f"`{_ZWSP}`{_ZWSP}`")
    return f"{out}\n(exit {rc})\n```\n{body}\n```"

def reply_text(text:str,        # reply body (markdown, not fenced)
               limit:int=2000,  # Discord message length cap
               )->str:          # len() <= limit, never empty
    "Tail-keeping truncation: the end of an answer matters most."
    body = text.strip()
    if not body: return "(no output)"
    if len(body) <= limit: return body
    marker = "… (truncated)\n"
    avail = limit - len(marker)
    if avail <= 0: return marker[:limit]   # degenerate cap: marker alone, clipped
    return marker + body[-avail:]
